### ISSUE TITLE
A offset for PBR's camera K

### ISSUE THREAD

**Issue by rcao-hk** [rasmushaugaard/surfemb#15]
Hi,

Thank you for your excellent work!
I just wondering why there is a 0.5 offset to compensate camera K for PBR data.
Thank you!

Best,
Rui

**Comment by rasmushaugaard** [comment]
Hi there
Thank you!

In the camera matrix provided with the PBR data, i presume the principal axis is in the center of the image and that the image origin is at the corner of the top left pixel, since cx=w/2.
In opencv however, the convention is to have the image origin in the center of the top left pixel.
